stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/raw/train.csv
    outs:
      - data/interim/cleaned_train.csv
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/interim/cleaned_train.csv
    outs:
      - data/processed/final_train.csv
  monitoring:
    cmd: python src/monitoring.py
    deps:
      - src/monitoring.py
      - data/raw/train.csv
      - data/prod.csv
    outs:
      - train_stats.json
      - data/monitoring/latest_report.json
      - data/monitoring/monitoring_dashboard.html
