stages:
  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/raw/train.csv
    outs:
      - data/interim/cleaned_train.csv
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/interim/cleaned_train.csv
    outs:
      - data/processed/final_train.csv
